#ifndef _TIMER_CONFIG_H
#define _TIMER_CONFIG_H


/* TIMER0_MODE:
 * Options:
 * TIMER_NORMAL_MODE
 * TIMER_PWM_PHASE_CORRECR_MODE
 * TIMER_CTC_MODE
 * TIMER_FAST_PWM_MODE
*/

#define TIMER0_MODE                              TIMER_PWM_PHASE_CORRECR_MODE

/* COMPARE_OUTPUT_SELECT_MODE:
 * Options:
 * TIMER_NORMAL_PORT
 * TIMER_TOGGLE_OC0_ON_COMPARE_MATCH 
 * TIMER_CLEAR_OC0_ON_COMPARE_MATCH
 * TIMER_SET_OC0_ON_COMPARE_MATCH
*/


#define TIMER0_CTC_SUB_MODE                             TIMER_SET_OC0_ON_COMPARE_MATCH

/* COMPARE_OUTPUT_SELECT_MODE:
 * Options:
 * TIMER_NORMAL_PORT
 * TIMER_CLR_ON_COMP_SET_ON_TOP 
 * TIMER_SET_ON_COMP_CLEAR_ON_TOP
 * TIMER_SET_ON_UP_COUNT_CLR_ON_DOWN_COUNT
 * TIMER_CLR_ON_UP_COUNT_SET_ON_DOWN_COUNT
*/

#define TIMER0_PWM_SUB_MODE                           TIMER_CLR_ON_UP_COUNT_SET_ON_DOWN_COUNT

                

/* TIMER0_COUNTER0_PRESCALER_SELECT:
 * Options:
 * TIMER_NO_CLK_SRC             
 * TIMER_NO_PRESCALING          
 * TIMER_PRESCALER_DIV_BY_8     
 * TIMER_PRESCALER_DIV_BY_64    
 * TIMER_PRESCALER_DIV_BY_256   
 * TIMER_PRESCALER_DIV_BY_1024  
 * COUNTER0_EXTI_CLK_RISING_EDGE 
 * COUNTER0_EXTI_CLK_FALLING_EDGE
*/

#define TIMER_COUNTER_PRESCALER_SELECT         TIMER_PRESCALER_DIV_BY_8

#define TIMER0_INTERRUT_SELECT                 OVF0_ENBLE


#define TIMER1_SELECT_MODE_A                   ICU_FAST_PWM_MODE_MSK_A
#define TIMER1_SELECT_MODE_B                   ICU_FAST_PWM_MODE_MSK_B

#define OC1A_CHANNEL                           ENABLE 
#define OC1B_CHANNEL                           DISABLE


#define TIMER1_MODE                            TIMER_FAST_PWM_MODE

#define TIMER1_SUB_MODE                        TIMER_CLR_ON_COMP_SET_ON_TOP

#endif
